[CCTRI-4182] Implement Attack Patterns mapping
CiscoSecurity/tr-05-serverless-ms-defender-for-office-365 pull request #11
Opened 2024-01-11 09:26 UTC by okslisovska

[[CCTRI-4182]](https://jira.softserveinc.com/browse/CCTRI-4182)

2024-01-11 15:16 UTC, grzegorzbielecki requested changes

2024-01-11 15:16 UTC, grzegorzbielecki commented on code/api/enrich.py
> +    techniques = re.findall(r"(T1\d{3}(?:\.\d{3})?)\)", techniques_str)
Maybe it is possible to compile this regular expression before the loop?

For example re.compile() can probably do that

2024-01-11 15:19 UTC, grzegorzbielecki commented on code/api/enrich.py
> +    techniques = re.findall(r"(T1\d{3}(?:\.\d{3})?)\)", techniques_str)
But I suppose python will optimise it anyway

2024-01-11 17:28 UTC, okslisovska commented on code/api/enrich.py
> +    techniques = re.findall(r"(T1\d{3}(?:\.\d{3})?)\)", techniques_str)
[Python docs](https://docs.python.org/3/library/re.html#:~:text=so%20programs%20that%20use%20only%20a%20few%20regular%20expressions%20at%20a%20time%20needn%E2%80%99t%20worry%20about%20compiling%20regular%20expressions.) says: "_programs that use only a few regular expressions at a time needn’t worry about compiling regular expressions_".

2024-01-15 15:04 UTC, Tempos approved these changes

2024-01-15 15:05 UTC, merged